const request = require('supertest');
const mongoose = require('mongoose');
const axios = require('axios');
const app = require('../server');

jest.mock('axios');

describe('Persistence Bridge Integration Tests', () => {
    
    beforeAll(async () => {
        const url = process.env.MONGO_URI || 'mongodb://mongodb:27017/test_db';
        if (mongoose.connection.readyState === 0) {
            await mongoose.connect(url);
        }
    });

    afterAll(async () => {
        if (mongoose.connection.readyState !== 0) {
            await mongoose.connection.db.dropDatabase();
            await mongoose.connection.close(); // MODIFICAT AICI
        }
    });

    // axios.post.mockResolvedValue tells the code: "The external validator said the string is valid.".
    // The code then proceeds to save the document to MongoDB.
    // It checks for a 201 status and confirms an _id was generated by the database.
    test('POST /blueprints - should save blueprint when validator returns true', async () => {
        axios.post.mockResolvedValue({ data: { isValid: true } });

        const response = await request(app)
            .post('/blueprints')
            .send({
                title: "Test Factory",
                blueprintString: "0eJ...",
                author: "Levent"
            });

        expect(response.statusCode).toBe(201);
        expect(response.body.title).toBe("Test Factory");
        expect(response.body).toHaveProperty('_id');
    });

    // The mock tells the code: "The external validator rejected this string.".
    // The bridge stops and does not save the data to MongoDB.
    // It returns a 400 error, proving that the bridge is correctly listening to the validator service.
    test('POST /blueprints - should fail when validator returns false', async () => {
        axios.post.mockResolvedValue({ data: { isValid: false } });

        const response = await request(app)
            .post('/blueprints')
            .send({
                title: "Bad String",
                blueprintString: "invalid",
                author: "Levent"
            });

        expect(response.statusCode).toBe(400);
        expect(response.body.error).toBe('Invalid Factorio String');
    });
});