stages:
  - test
  - build

# AUTH tests
test_auth:
  stage: test
  image: python:3.10-slim
  services:
    - name: mongo:latest
      alias: mongodb
  variables:
    MONGO_DETAILS: "mongodb://mongodb:27017"
  only:
    changes:
      - auth-service/**/*
  script:
    - cd auth-service
    - pip install --no-cache-dir -r requirements.txt
    - python3 -m pytest tests/test_auth.py

# BLUEPRINT-LOGIC tests
test_blueprint-logic:
  stage: test
  image: node:18-slim
  only:
    changes:
      - blueprint-logic/**/*
  script:
    - cd blueprint-logic
    - npm install
    - npx jest --passWithNoTests

build_auth:
  stage: build
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  only:
    changes:
      - auth-service/**/*
  script:
    - cd auth-service
    - sleep 5 
    - docker info
    - docker build -t factorio-auth-service:$CI_COMMIT_SHORT_SHA .

build_blueprint-logic:
  stage: build
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: ""
  only:
    changes:
      - blueprint-logic/**/*
  script:
    - cd blueprint-logic
    - docker build -t factorio-logic-service:$CI_COMMIT_SHORT_SHA .