stages:
  - test
  - build

test_auth:
  stage: test
  image: python:3.10-slim
  services:
    - name: mongo:latest
      alias: mongodb
  variables:
    MONGO_DETAILS: "mongodb://mongodb:27017"
  only:
    changes:
      - auth-service/**/*
  script:
    - cd auth-service
    - pip install --no-cache-dir -r requirements.txt
    # This is the line that needs changing:
    - python3 -m pytest tests/test_auth.py

build_auth:
  stage: build
  image: docker:24.0
  services:
    - name: docker:24.0-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375  # Forțează comunicarea prin TCP către serviciu
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  only:
    changes:
      - auth-service/**/*
  script:
    - cd auth-service
    # Așteptăm câteva secunde ca serviciul Docker să pornească efectiv
    - sleep 5 
    - docker info # Comandă de debug pentru a vedea dacă se conectează
    - docker build -t factorio-auth-service:$CI_COMMIT_SHORT_SHA .