apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: logic-service
  name: logic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logic-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/proiect-idp-gateway-network: "true"
        io.kompose.network/proiect-idp-internal-network: "true"
        io.kompose.service: logic-service
    spec:
      containers:
        - image: proiect-idp-logic-service:latest
          name: logic-service
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
