apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: persistence-bridge
  name: persistence-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: persistence-bridge
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/proiect-idp-app-network: "true"
        io.kompose.network/proiect-idp-db-network: "true"
        io.kompose.network/proiect-idp-internal-network: "true"
        io.kompose.service: persistence-bridge
    spec:
      containers:
        - env:
            - name: MONGO_URI
              value: mongodb://mongodb:27017/blueprints_db
            - name: VALIDATOR_URL
              value: http://validator-service:3000/validate
          image: proiect-idp-persistence-bridge:latest
          name: persistence-bridge
          imagePullPolicy: Never
          resources: {}
      restartPolicy: Always
status: {}
