apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: prometheus
    spec:
      containers:
        - image: prom/prometheus:latest
          imagePullPolicy: IfNotPresent # Pentru imagini de pe internet e mai safe IfNotPresent
          name: prometheus
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            # Aici montăm fișierul de configurare
            - mountPath: /etc/prometheus/prometheus.yml
              name: prometheus-config-volume
              subPath: prometheus.yml
            - mountPath: /prometheus
              name: prometheus-data
      restartPolicy: Always
      volumes:
        # Aici definim sursa fișierului din ConfigMap
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
        - name: prometheus-data
          persistentVolumeClaim:
            claimName: prometheus-data